export const categories = [
  {
    name: 'Men’s',
  },
  {
    name: 'Women’s',
  },
  {
    name: 'Women Accessories',
  },
  {
    name: 'Men Accessories',
  },
  {
    name: 'Discount Deals',
  },
];

export const brands = [
  {
    name: 'Aape',
  },
  {
    name: 'Adidas',
  },
  {
    name: 'Columbia',
  },
  {
    name: 'Polo Ralph Lauren',
  },
  {
    name: 'The North Face',
  },
  {
    name: 'Daisy Street',
  },
  {
    name: 'Hollister',
  },
  {
    name: 'Simmi',
  },
  {
    name: 'ASOS',
  },
  {
    name: 'Pull&Bear',
  },
  {
    name: 'Classics 77',
  },
  {
    name: 'Faded Future',
  },
];

export const sizes = [
  {
    name: 'XXS',
  },
  {
    name: 'XS',
  },
  {
    name: 'S',
  },
  {
    name: 'M',
  },
  {
    name: 'L',
  },
  {
    name: 'XL',
  },
  {
    name: 'XXL',
  },
  {
    name: 'XXXL',
  },
];

export const products = [
  {
    img: 'aape-1/205316648-1-grey.avif',
    name: 'Aape By A Bathing Ape ribbed beanie in grey',
    price: 32.0,
    rating: 4.0,
    categoryId: 1,
    tags: [{ id: 1 }, { id: 2 }],
    stock: 6,
    brandId: 1,
    sizes: [{ id: 1 }, { id: 2 }],
  },
  {
    img: 'aape-2/205915130-1-green.avif',
    name: 'Aape By A Bathing Ape regular fit short sleeve t-shirt with front print in green',
    price: 32.0,
    rating: 5.0,
    categoryId: 1,
    tags: [{ id: 1 }, { id: 2 }],
    stock: 18,
    saleId: 2,
    brandId: 1,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'aape-3/205914431-1-white.avif',
    name: 'Aape By A Bathing Ape regular fit short sleeve t-shirt with back graphic in white',
    price: 71.0,
    rating: 4.9,
    categoryId: 1,
    tags: [{ id: 1 }, { id: 2 }],
    stock: 15,
    brandId: 1,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'adidas-1/206071751-1-black.avif',
    name: 'adidas Originals Adibreak sweatshirt in black and grey',
    price: 43.5,
    rating: 5.0,
    categoryId: 1,
    tags: [{ id: 1 }, { id: 2 }],
    stock: 48,
    saleId: 1,
    brandId: 2,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'adidas-2/205473692-1-khaki.avif',
    name: 'adidas sweatshirt in khaki',
    price: 23.0,
    rating: 4.3,
    categoryId: 1,
    stock: 6,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 2,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'adidas-3/206203227-1-white.avif',
    name: 'adidas Originals Tennis unisex graphic t-shirt in white',
    price: 17.3,
    rating: 4.2,
    categoryId: 1,
    stock: 8,
    saleId: 2,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 2,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'columbia-1/205503146-2.avif',
    name: 'Columbia CSC Basic logo t-shirt in black',
    price: 24.0,
    rating: 4.9,
    categoryId: 1,
    stock: 11,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 3,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'columbia-2/205620001-1-chalk.avif',
    name: 'Columbia Reventure quarter zip sweater in chalk',
    price: 35.7,
    rating: 4.4,
    categoryId: 1,
    stock: 24,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 3,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'columbia-3/205620534-1-black.avif',
    name: 'Columbia Reventure crew neck sweat in black',
    price: 28.0,
    rating: 5.0,
    categoryId: 1,
    stock: 16,
    tags: [{ id: 1 }, { id: 2 }],
    saleId: 3,
    brandId: 3,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'polo-ralph-lauren-1/205995948-1-blue.avif',
    name: 'Polo Ralph Lauren Sport Capsule long sleeve shirt in blue',
    price: 74.2,
    rating: 4.6,
    categoryId: 1,
    stock: 4,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 4,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'polo-ralph-lauren-2/206498221-1-black.avif',
    name: 'Polo Ralph Lauren icon logo lined hooded windbreaker in black',
    price: 28.0,
    rating: 3.9,
    categoryId: 1,
    stock: 9,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 4,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'polo-ralph-lauren-3/205512628-1-brown.avif',
    name: 'Polo Ralph Lauren logo front sherpa borg hoodie in brown',
    price: 120.99,
    rating: 4.4,
    categoryId: 1,
    stock: 14,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 4,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'tnf-1/205762983-1-cream.avif',
    name: 'The North Face Berkeley California large logo t-shirt in off white',
    price: 80.0,
    rating: 4.8,
    categoryId: 1,
    stock: 33,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 5,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'tnf-2/205418018-1-grey.avif',
    name: 'The North Face Aconcagua 3 down puffer jacket in grey',
    price: 83.0,
    rating: 5.0,
    categoryId: 1,
    stock: 15,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 5,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'tnf-3/205417897-1-black.avif',
    name: 'The North Face Himalayan Insulated puffer gilet in black',
    price: 54.5,
    rating: 5.0,
    categoryId: 1,
    stock: 18,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 5,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'daysi-street-1/206596379-1-grey.avif',
    name: 'Daisy Street relaxed sweatshirt in grey',
    price: 54.5,
    rating: 5.0,
    categoryId: 2,
    stock: 12,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 6,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'daysi-street-2/206032201-1-washedblue.avif',
    name: 'Daisy Street relaxed t-shirt in washed blue with dolphin graphic',
    price: 43.5,
    rating: 5.0,
    categoryId: 2,
    stock: 5,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 6,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'daysi-street-3/206508400-1-multi.avif',
    name: 'Daisy Street boxy rugby sweatshirt in cherry red stripe',
    price: 32.0,
    rating: 5.0,
    categoryId: 2,
    stock: 22,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 6,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'hollister-1/207361782-1-mocha.avif',
    name: 'Hollister cable knitted high neck cropped jacket in mocha',
    price: 65.0,
    rating: 5.0,
    categoryId: 2,
    stock: 2,
    tags: [{ id: 1 }, { id: 2 }],
    saleId: 3,
    brandId: 7,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'hollister-2/206971725-1-brown.avif',
    name: 'Hollister mini puffer vest in brown',
    price: 71.4,
    rating: 5.0,
    categoryId: 2,
    stock: 5,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 7,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'hollister-3/205681323-1-black.avif',
    name: 'Hollister slim fit square neck jumper with flute sleeves in black',
    price: 74.0,
    rating: 5.0,
    categoryId: 2,
    stock: 18,
    tags: [{ id: 1 }, { id: 2 }],
    saleId: 1,
    brandId: 7,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'simmi-1/206490230-1-black.avif',
    name: 'Simmi slinky bardot foldover top in black',
    price: 43.0,
    rating: 5.0,
    categoryId: 2,
    stock: 7,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 8,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'simmi-2/206521173-1-whitegrey.avif',
    name: 'Simmi high neck knitted mini dress in grey geo print',
    price: 38.0,
    rating: 5.0,
    categoryId: 2,
    stock: 11,
    tags: [{ id: 1 }, { id: 2 }],
    saleId: 3,
    brandId: 8,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/asos-1/205944896-1-grey.avif',
    name: 'ASOS DESIGN large slouchy sling tote bag in grey',
    price: 23.0,
    rating: 5.0,
    categoryId: 3,
    stock: 18,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 9,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/asos-2/206956978-1-burgundy.avif',
    name: 'ASOS DESIGN shoulder bag with buckle detail in burgundy',
    price: 21.0,
    rating: 5.0,
    categoryId: 3,
    stock: 24,
    tags: [{ id: 1 }, { id: 2 }],
    saleId: 1,
    brandId: 9,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/asos-3/205186742-1-black.avif',
    name: 'ASOS DESIGN oversized heavyweight canvas tote bag in black',
    price: 19.0,
    rating: 5.0,
    categoryId: 3,
    stock: 32,
    tags: [{ id: 1 }, { id: 2 }],
    saleId: 3,
    brandId: 9,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/pull&bear-1/207165975-1-black.avif',
    name: 'Pull&Bear patent shoulder bag with flap detail in black',
    price: 28.0,
    rating: 5.0,
    categoryId: 3,
    stock: 23,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 10,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/pull&bear-2/207196099-1-charcoal.avif',
    name: 'Pull&Bear metal strap detail shoulder bag in grey wash',
    price: 26.2,
    rating: 5.0,
    categoryId: 3,
    stock: 9,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 10,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/pull&bear-3/206997820-1-darkgreen.avif',
    name: 'Pull&Bear crochet shoulder bag in olive green',
    price: 17.9,
    rating: 5.0,
    categoryId: 3,
    stock: 6,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 10,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/classic77-1/206525804-1-silver.avif',
    name: 'Classics 77 flower peace pendant necklace in silver',
    price: 11.9,
    rating: 5.0,
    categoryId: 4,
    stock: 16,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 11,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/classic77-2/206525691-1-white.avif',
    name: 'Classics 77 earthland bead and cord bracelet in cream',
    price: 9.9,
    rating: 5.0,
    categoryId: 4,
    stock: 19,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 11,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/classic77-3/206525836-1-silver.avif',
    name: 'Classics 77 sun engraved link bracelet in silver',
    price: 12.0,
    rating: 5.0,
    categoryId: 4,
    stock: 29,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 11,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/faded-future-1/206892066-1-silver.avif',
    name: 'Faded Future chain bracelet with quilt pattern pendant in silver',
    price: 17.0,
    rating: 5.0,
    categoryId: 4,
    stock: 23,
    tags: [{ id: 1 }],
    saleId: 2,
    brandId: 12,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/faded-future-2/206892159-1-silver.avif',
    name: 'Faded Future quilt pattern pendant in silver',
    price: 15.4,
    rating: 5.0,
    categoryId: 4,
    stock: 8,
    tags: [{ id: 1 }, { id: 2 }],
    saleId: 1,
    brandId: 12,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
  {
    img: 'accessories/faded-future-3/206892141-1-gold.avif',
    name: 'Faded Future herringbone chain necklace in gold',
    price: 17.6,
    rating: 5.0,
    categoryId: 4,
    stock: 48,
    tags: [{ id: 1 }, { id: 2 }],
    brandId: 12,
    sizes: [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
  },
];
