// export const categories = [
//   {
//     name: 'Men’s',
//   },
//   {
//     name: 'Women’s',
//   },
//   {
//     name: 'Women Accessories',
//   },
//   {
//     name: 'Men Accessories',
//   },
//   {
//     name: 'Discount Deals',
//   },
// ];

export const categories = [
  { name: "Men's Clothing" }, // 1
  { name: "Women's Clothing" }, // 2
  { name: 'Outerwear' }, // 3
  { name: 'T-shirts & Shirts' }, // 4
  { name: 'Hoodies & Sweaters' }, // 5
  { name: 'Pants & Trousers' }, // 6
  { name: 'Dresses & Skirts' }, // 7
  { name: 'Sneakers & Sports Shoes' }, // 8
  { name: 'Bags & Accessories' }, // 9
  { name: 'Winter Clothing' }, // 10
  { name: 'Hats & Headwear' }, // 11
  { name: 'Sportswear' }, // 12
  { name: 'Women Accessories' }, // 13
  { name: 'Men Accessories' }, // 14
];

export const collections = [
  { name: 'Discount' }, // 1
  { name: 'New Arrivals' }, // 2
  { name: 'Deals' }, // 3
];

export const sales = [
  {
    name: 'Black Friday',
    percent: 50,
  },
  {
    name: 'Super Sale',
    percent: 20,
  },
  {
    name: 'Spring Sale',
    percent: 15,
  },
];

export const brands = [
  {
    name: 'Aape',
  },
  {
    name: 'Adidas',
  },
  {
    name: 'Columbia',
  },
  {
    name: 'Polo Ralph Lauren',
  },
  {
    name: 'The North Face',
  },
  {
    name: 'Daisy Street',
  },
  {
    name: 'Hollister',
  },
  {
    name: 'Simmi',
  },
  {
    name: 'ASOS',
  },
  {
    name: 'Pull&Bear',
  },
  {
    name: 'Classics 77',
  },
  {
    name: 'Faded Future',
  },
];

export const sizes = [
  {
    name: 'XS',
  },
  {
    name: 'S',
  },
  {
    name: 'M',
  },
  {
    name: 'L',
  },
  {
    name: 'XL',
  },
  {
    name: 'XXL',
  },
];

export const products = [
  {
    img: 'aape-1/205316648-1-grey.avif',
    name: 'Aape By A Bathing Ape ribbed beanie in grey',
    price: 32.0,
    rating: 4.0,
    stock: 23,
    categories: [{ id: 11 }],
    collections: [{ id: 1 }, { id: 2 }],
    sizes: [],
    brandId: 1,
    saleNameId: 1,
  },
  {
    img: 'aape-2/205915130-1-green.avif',
    name: 'Aape By A Bathing Ape regular fit short sleeve t-shirt with front print in green',
    price: 32.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 4 }],
    collections: [{ id: 1 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 1,
    saleNameId: 3,
  },
  {
    img: 'aape-3/205914431-1-white.avif',
    name: 'Aape By A Bathing Ape regular fit short sleeve t-shirt with back graphic in white',
    price: 71.0,
    rating: 4.9,
    stock: 0,
    categories: [{ id: 1 }, { id: 4 }],
    collections: [{ id: 2 }, { id: 3 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 1,
    saleNameId: 3,
  },
  {
    img: 'adidas-1/206071751-1-black.avif',
    name: 'adidas Originals Adibreak sweatshirt in black and grey',
    price: 43.5,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 1 }, { id: 5 }],
    collections: [],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 2,
    saleNameId: null,
  },
  {
    img: 'adidas-2/205473692-1-khaki.avif',
    name: 'adidas sweatshirt in khaki',
    price: 23.0,
    rating: 4.3,
    stock: 0,
    categories: [{ id: 1 }, { id: 5 }],
    collections: [{ id: 2 }, { id: 3 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 2,
    saleNameId: null,
  },
  {
    img: 'adidas-3/206203227-1-white.avif',
    name: 'adidas Originals Tennis unisex graphic t-shirt in white',
    price: 17.3,
    rating: 4.2,
    stock: 0,
    categories: [{ id: 1 }, { id: 2 }, { id: 4 }],
    collections: [{ id: 2 }, { id: 3 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 2,
    saleNameId: 1,
  },
  {
    img: 'columbia-1/205503146-2.avif',
    name: 'Columbia CSC Basic logo t-shirt in black',
    price: 24.0,
    rating: 4.9,
    stock: 0,
    categories: [{ id: 1 }, { id: 4 }],
    collections: [{ id: 1 }, { id: 3 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 3,
    saleNameId: 3,
  },
  {
    img: 'columbia-2/205620001-1-chalk.avif',
    name: 'Columbia Reventure quarter zip sweater in chalk',
    price: 35.7,
    rating: 4.4,
    stock: 0,
    categories: [{ id: 1 }, { id: 5 }],
    collections: [{ id: 2 }, { id: 3 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 3,
    saleNameId: 2,
  },
  {
    img: 'columbia-3/205620534-1-black.avif',
    name: 'Columbia Reventure crew neck sweat in black',
    price: 28.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 1 }, { id: 5 }],
    collections: [{ id: 1 }, { id: 3 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 3,
    saleNameId: 2,
  },
  {
    img: 'polo-ralph-lauren-1/205995948-1-blue.avif',
    name: 'Polo Ralph Lauren Sport Capsule long sleeve shirt in blue',
    price: 74.2,
    rating: 4.6,
    stock: 0,
    categories: [{ id: 1 }, { id: 4 }],
    collections: [{ id: 1 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 4,
    saleNameId: 2,
  },
  {
    img: 'polo-ralph-lauren-2/206498221-1-black.avif',
    name: 'Polo Ralph Lauren icon logo lined hooded windbreaker in black',
    price: 28.0,
    rating: 3.9,
    stock: 0,
    categories: [{ id: 1 }, { id: 5 }],
    collections: [{ id: 1 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 4,
    saleNameId: 1,
  },
  {
    img: 'polo-ralph-lauren-3/205512628-1-brown.avif',
    name: 'Polo Ralph Lauren logo front sherpa borg hoodie in brown',
    price: 120.99,
    rating: 4.4,
    stock: 0,
    categories: [{ id: 1 }, { id: 5 }],
    collections: [{ id: 2 }, { id: 3 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 4,
    saleNameId: 3,
  },
  {
    img: 'tnf-1/205762983-1-cream.avif',
    name: 'The North Face Berkeley California large logo t-shirt in off white',
    price: 80.0,
    rating: 4.8,
    stock: 0,
    categories: [{ id: 1 }, { id: 4 }],
    collections: [{ id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 5,
    saleNameId: null,
  },
  {
    img: 'tnf-2/205418018-1-grey.avif',
    name: 'The North Face Aconcagua 3 down puffer jacket in grey',
    price: 83.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 1 }, { id: 3 }],
    collections: [{ id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 5,
    saleNameId: null,
  },
  {
    img: 'tnf-3/205417897-1-black.avif',
    name: 'The North Face Himalayan Insulated puffer gilet in black',
    price: 54.5,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 1 }, { id: 3 }],
    collections: [{ id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 5,
    saleNameId: null,
  },
  {
    img: 'daysi-street-1/206596379-1-grey.avif',
    name: 'Daisy Street relaxed sweatshirt in grey',
    price: 54.5,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 2 }, { id: 5 }],
    collections: [{ id: 3 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 6,
    saleNameId: 1,
  },
  {
    img: 'daysi-street-2/206032201-1-washedblue.avif',
    name: 'Daisy Street relaxed t-shirt in washed blue with dolphin graphic',
    price: 43.5,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 2 }, { id: 4 }],
    collections: [{ id: 1 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 6,
    saleNameId: 3,
  },
  {
    img: 'daysi-street-3/206508400-1-multi.avif',
    name: 'Daisy Street boxy rugby sweatshirt in cherry red stripe',
    price: 32.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 2 }, { id: 5 }],
    collections: [{ id: 1 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 6,
    saleNameId: 3,
  },
  {
    img: 'hollister-1/207361782-1-mocha.avif',
    name: 'Hollister cable knitted high neck cropped jacket in mocha',
    price: 65.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 2 }, { id: 3 }],
    collections: [{ id: 1 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 7,
    saleNameId: 3,
  },
  {
    img: 'hollister-2/206971725-1-brown.avif',
    name: 'Hollister mini puffer vest in brown',
    price: 71.4,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 2 }, { id: 3 }],
    collections: [{ id: 1 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 7,
    saleNameId: 3,
  },
  {
    img: 'hollister-3/205681323-1-black.avif',
    name: 'Hollister slim fit square neck jumper with flute sleeves in black',
    price: 74.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 2 }, { id: 5 }],
    collections: [{ id: 2 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 7,
    saleNameId: null,
  },
  {
    img: 'simmi-1/206490230-1-black.avif',
    name: 'Simmi slinky bardot foldover top in black',
    price: 43.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 2 }, { id: 4 }],
    collections: [{ id: 3 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 8,
    saleNameId: null,
  },
  {
    img: 'simmi-2/206521173-1-whitegrey.avif',
    name: 'Simmi high neck knitted mini dress in grey geo print',
    price: 38.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 2 }, { id: 7 }],
    collections: [{ id: 2 }, { id: 3 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 8,
    saleNameId: 1,
  },
  {
    img: 'accessories/asos-1/205944896-1-grey.avif',
    name: 'ASOS DESIGN large slouchy sling tote bag in grey',
    price: 23.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 13 }, { id: 9 }],
    collections: [{ id: 1 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 9,
    saleNameId: 2,
  },
  {
    img: 'accessories/asos-2/206956978-1-burgundy.avif',
    name: 'ASOS DESIGN shoulder bag with buckle detail in burgundy',
    price: 21.0,
    rating: 3.3,
    stock: 0,
    categories: [{ id: 13 }, { id: 9 }],
    collections: [{ id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 9,
    saleNameId: 2,
  },
  {
    img: 'accessories/asos-3/205186742-1-black.avif',
    name: 'ASOS DESIGN oversized heavyweight canvas tote bag in black',
    price: 19.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 13 }, { id: 9 }],
    collections: [{ id: 2 }, { id: 3 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 9,
    saleNameId: null,
  },
  {
    img: 'accessories/pull&bear-1/207165975-1-black.avif',
    name: 'Pull&Bear patent shoulder bag with flap detail in black',
    price: 28.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 13 }, { id: 9 }],
    collections: [{ id: 2 }, { id: 3 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 10,
    saleNameId: null,
  },
  {
    img: 'accessories/pull&bear-2/207196099-1-charcoal.avif',
    name: 'Pull&Bear metal strap detail shoulder bag in grey wash',
    price: 26.2,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 13 }, { id: 9 }],
    collections: [{ id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 10,
    saleNameId: null,
  },
  {
    img: 'accessories/pull&bear-3/206997820-1-darkgreen.avif',
    name: 'Pull&Bear crochet shoulder bag in olive green',
    price: 17.9,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 13 }, { id: 9 }],
    collections: [{ id: 1 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 10,
    saleNameId: 3,
  },
  {
    img: 'accessories/classic77-1/206525804-1-silver.avif',
    name: 'Classics 77 flower peace pendant necklace in silver',
    price: 11.9,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 14 }, { id: 9 }],
    collections: [{ id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 11,
    saleNameId: null,
  },
  {
    img: 'accessories/classic77-2/206525691-1-white.avif',
    name: 'Classics 77 earthland bead and cord bracelet in cream',
    price: 9.9,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 14 }, { id: 9 }],
    collections: [{ id: 3 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 11,
    saleNameId: null,
  },
  {
    img: 'accessories/classic77-3/206525836-1-silver.avif',
    name: 'Classics 77 sun engraved link bracelet in silver',
    price: 12.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 14 }, { id: 9 }],
    collections: [{ id: 3 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 11,
    saleNameId: null,
  },
  {
    img: 'accessories/faded-future-1/206892066-1-silver.avif',
    name: 'Faded Future chain bracelet with quilt pattern pendant in silver',
    price: 17.0,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 14 }, { id: 9 }],
    collections: [{ id: 2 }, { id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 12,
    saleNameId: null,
  },
  {
    img: 'accessories/faded-future-2/206892159-1-silver.avif',
    name: 'Faded Future quilt pattern pendant in silver',
    price: 15.4,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 14 }, { id: 9 }],
    collections: [{ id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 12,
    saleNameId: null,
  },
  {
    img: 'accessories/faded-future-3/206892141-1-gold.avif',
    name: 'Faded Future herringbone chain necklace in gold',
    price: 17.6,
    rating: 5.0,
    stock: 0,
    categories: [{ id: 14 }, { id: 9 }],
    collections: [{ id: 2 }],
    sizes: [
      { sizeId: 1, quantity: 4 },
      { sizeId: 2, quantity: 2 },
      { sizeId: 3, quantity: 3 },
      { sizeId: 4, quantity: 0 },
      { sizeId: 5, quantity: 2 },
      { sizeId: 6, quantity: 6 },
    ],
    brandId: 12,
    saleNameId: null,
  },
];
